var defaultError = module.exports = {
    isEmail: 'Invalid email',
    isUrl: 'Invalid URL',
    isIP: 'Invalid IP',
    isAlpha: 'The %field may only contain letters.',
    isAlphanumeric: 'The %field may only contain letters and numbers.',
    isHexadecimal: 'Invalid hexadecimal',
    isHexColor: 'Invalid hexcolor',
    isNumeric: 'The %field must be a number.',
    isLowercase: 'The %field may only contain lowercase letters.',
    isUppercase: 'The %field may only contain uppercase letters.',
    isInt: 'The %field must be an integer',
    isDecimal: 'The %field must be a decimal',
    isDivisibleBy: 'The %field must be divisible by %1.',
    notNull: 'The %field is required',
    isNull: 'String is not empty',
    notEmpty: 'The %field should not be blank.',
    equals: 'The %field must equals to %1',
    contains: 'Invalid characters',
    notContains: 'Invalid characters',
    regex: 'The %field format is invalid',
    notRegex: 'The %field format is invalid',
    len: 'The %field must contain between %1 and %2 characters',
    isUUID: 'Not a UUID',
    isUUIDv3: 'Not a UUID v3',
    isUUIDv4: 'Not a UUID v4',
    isUUIDv5: 'Not a UUID v5',
    isDate: 'Invalid Date format',
    isAfter: 'Invalid date',
    isBefore: 'Invalid date',
    isIn: 'Unexpected value or invalid argument',
    notIn: 'Unexpected value or invalid argument',
    min: 'The %field value must be at least %1 characters',
    max: 'Invalid number',
    isArray: 'Not an array',
    isCreditCard: 'Invalid credit card',
    same: 'The %field confirmation does not match.'
};
